
FROM ruby:3.3.6
RUN apt-get update -qq && \
    apt-get install -y nodejs build-essential postgresql-client
WORKDIR /app

ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID appgroup && \
    useradd -u $UID -g appgroup -m appuser && \
    mkdir -p /usr/local/bundle && \
    chown -R appuser:appgroup /usr/local/bundle

USER appuser

COPY --chown=appuser:appgroup Gemfile Gemfile.lock ./
RUN bundle install
COPY --chown=appuser:appgroup . .

EXPOSE 3000
CMD ["bash", "-lc", "bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"]
